version: '3'

services:
  database_stage:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./dados_mongo:/data/db

  api_stage:
    image: rozaworks/user-account-api
    environment:
      DB_HOST: database_stage
    ports:
      - "9090:9090"

volumes:
  db-volume:
