version: '3'

services:
  database_stage:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - ./dados_mongo:/data/db

  api_stage:
    image: gianbueno/platform
    environment:
      DB_HOST: database_stage
    ports:
      - "9191:9191"

volumes:
  db-volume:
